before_script:
- apt-get update -qy

test:
  script:
  - apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev
  - wget https://www.python.org/ftp/python/3.7.0/Python-3.7.0.tgz
  - tar -xzf Python-3.7.0.tgz
  - cd Python-3.7.0
  - ./configure
  - make altinstall
  - cd ..
  - pip3.7 install -r requirements.txt
  - pytest

production:
  type: deploy
  only:
  - master
  script:
  - 'which ssh-agent || ( apt-get install -y openssh-client )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - chmod 700 ~/.ssh
  - ssh remote /srv/update.sh
