test:
  script:
  - apt-get update -qy
  - apt-get instlal python-dev python-pip
  - pip install -r requirements.txt
  - pytest

production:
  type: deploy
  only:
  - master
  script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - chmod 700 ~/.ssh
  - ssh remote /srv/update.sh
