[metadata.heroku]
  root-package = "github.com/celeo/playbypost/server"

[[constraint]]
  branch = "dev"
  name = "github.com/celeo/getin-backend"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/jmoiron/sqlx"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "1.6.0"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"
