[metadata.heroku]
  root-package = "github.com/celeo/playbypost/server"

[[constraint]]
  branch = "dev"
  name = "github.com/celeo/getin-backend"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/jmoiron/sqlx"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  branch = "master"
  name = "github.com/nu7hatch/gouuid"

[[constraint]]
  name = "github.com/itsjamie/gin-cors"
  version = "1.0.0"
